openapi: 3.1.0
info:
  description: API documentation for organizations-svc
  title: organizations-svc API
  version: 0.1.0
servers:
- url: /
paths:
  /test:
    post:
      description: Test
      responses:
        "201":
          description: successfully
      tags:
      - Test
components:
  schemas:
    CreateOrganization:
      properties:
        data:
          $ref: "#/components/schemas/CreateOrganization_data"
      required:
      - data
    UpdateOrganization:
      properties:
        data:
          $ref: "#/components/schemas/UpdateOrganization_data"
      required:
      - data
    UpdateMember:
      properties:
        data:
          $ref: "#/components/schemas/UpdateMember_data"
      required:
      - data
    CreateInvite:
      properties:
        data:
          $ref: "#/components/schemas/CreateInvite_data"
      required:
      - data
    CreateRole:
      properties:
        data:
          $ref: "#/components/schemas/CreateRole_data"
      required:
      - data
    UpdateRole:
      properties:
        data:
          $ref: "#/components/schemas/UpdateRole_data"
      required:
      - data
    UpdateRolesRanks:
      properties:
        data:
          $ref: "#/components/schemas/UpdateRolesRanks_data"
      required:
      - data
    UpdateRolePermissions:
      properties:
        data:
          $ref: "#/components/schemas/UpdateRolePermissions_data"
      required:
      - data
    PaginationData:
      properties:
        self:
          description: link to the current page
          format: uri
          type: string
        first:
          description: link to the first page
          format: uri
          type: string
        last:
          description: link to the last page
          format: uri
          type: string
        prev:
          description: link to the previous page
          format: uri
          type: string
        next:
          description: link to the next page
          format: uri
          type: string
      required:
      - self
    Organization:
      properties:
        data:
          $ref: "#/components/schemas/Organization_data"
      required:
      - data
    OrganizationsCollection:
      properties:
        data:
          items:
            $ref: "#/components/schemas/Organization/properties/data"
          type: array
        links:
          $ref: "#/components/schemas/PaginationData"
      required:
      - data
      - links
    Member:
      properties:
        data:
          $ref: "#/components/schemas/Member_data"
      required:
      - data
    MemberCollection:
      properties:
        data:
          items:
            $ref: "#/components/schemas/Member/properties/data"
          type: array
        links:
          $ref: "#/components/schemas/PaginationData"
      required:
      - data
      - links
    Invite:
      properties:
        data:
          $ref: "#/components/schemas/Invite_data"
      required:
      - data
    InvitesCollection:
      properties:
        data:
          items:
            $ref: "#/components/schemas/Invite/properties/data"
          type: array
        links:
          $ref: "#/components/schemas/PaginationData"
      required:
      - data
      - links
    Role:
      properties:
        data:
          $ref: "#/components/schemas/Role_data"
      required:
      - data
    RolesCollection:
      properties:
        data:
          items:
            $ref: "#/components/schemas/Role/properties/data"
          type: array
        links:
          $ref: "#/components/schemas/PaginationData"
      required:
      - data
      - links
    RolePermissions:
      properties:
        data:
          items:
            $ref: "#/components/schemas/RolePermissions_data_inner"
          type: array
      required:
      - data
    data:
      properties:
        id:
          description: member ID
          format: uuid
          type: string
        type:
          enum:
          - role
          type: string
        attributes:
          $ref: "#/components/schemas/Role_data_attributes"
        relationships:
          $ref: "#/components/schemas/Role_data_relationships"
      required:
      - attributes
      - id
      - type
    CreateOrganization_data_attributes:
      properties:
        name:
          description: The name of the organization
          type: string
        icon:
          description: The icon representing the organization
          type: string
      required:
      - name
    CreateOrganization_data:
      properties:
        type:
          enum:
          - organization
          type: string
        attributes:
          $ref: "#/components/schemas/CreateOrganization_data_attributes"
      required:
      - attributes
      - type
    UpdateOrganization_data_attributes:
      properties:
        name:
          description: The name of the organization
          type: string
        icon:
          description: The icon representing the organization
          type: string
    UpdateOrganization_data:
      properties:
        id:
          description: organization ID
          format: uuid
          type: string
        type:
          enum:
          - organization
          type: string
        attributes:
          $ref: "#/components/schemas/UpdateOrganization_data_attributes"
      required:
      - attributes
      - id
      - type
    UpdateMember_data_attributes:
      properties:
        position:
          description: The position or role of the member within the organization
          type: string
        label:
          description: A label or title associated with the member
          type: string
    UpdateMember_data:
      properties:
        id:
          description: member ID
          format: uuid
          type: string
        type:
          enum:
          - update_member
          type: string
        attributes:
          $ref: "#/components/schemas/UpdateMember_data_attributes"
      required:
      - attributes
      - id
      - type
    CreateInvite_data_attributes:
      properties:
        organization_id:
          description: The ID of the organization to which the invite belongs
          format: uuid
          type: string
        account_id:
          description: The ID of the account that was invited
          format: uuid
          type: string
      required:
      - account_id
      - organization_id
    CreateInvite_data:
      properties:
        type:
          enum:
          - create_invite
          type: string
        attributes:
          $ref: "#/components/schemas/CreateInvite_data_attributes"
      required:
      - attributes
      - type
    CreateRole_data_attributes:
      properties:
        organization_id:
          description: The ID of the organization this role belongs to
          format: uuid
          type: string
        rank:
          description: The rank of the role within the organization
          format: uint
          type: integer
        name:
          description: The name of the role
          type: string
        description:
          description: A brief description of the role
          type: string
        color:
          description: The color associated with the role in HEX format
          type: string
      required:
      - color
      - description
      - name
      - organization_id
      - rank
    CreateRole_data:
      properties:
        type:
          enum:
          - create_role
          type: string
        attributes:
          $ref: "#/components/schemas/CreateRole_data_attributes"
      required:
      - attributes
      - type
    UpdateRole_data_attributes:
      properties:
        name:
          description: The name of the role
          type: string
        description:
          description: A brief description of the role
          type: string
        color:
          description: The color associated with the role in HEX format
          type: string
    UpdateRole_data:
      properties:
        id:
          description: role ID
          format: uuid
          type: string
        type:
          enum:
          - update_role
          type: string
        attributes:
          $ref: "#/components/schemas/UpdateRole_data_attributes"
      required:
      - attributes
      - id
      - type
    UpdateRolesRanks_data_attributes_roles_inner:
      properties:
        id:
          description: role ID
          format: uuid
          type: string
        rank:
          description: The new rank of the role in the hierarchy
          format: uint
          type: integer
      required:
      - id
      - rank
    UpdateRolesRanks_data_attributes:
      properties:
        roles:
          description: An ordered list of role IDs representing the new roles hierarchy
          items:
            $ref: "#/components/schemas/UpdateRolesRanks_data_attributes_roles_inner"
          type: array
    UpdateRolesRanks_data:
      properties:
        id:
          description: organization ID
          format: uuid
          type: string
        type:
          enum:
          - update_roles_ranks
          type: string
        attributes:
          $ref: "#/components/schemas/UpdateRolesRanks_data_attributes"
      required:
      - attributes
      - id
      - type
    UpdateRolePermissions_data_attributes_permissions_inner:
      properties:
        code:
          description: permission code
          type: string
        status:
          description: The new status of the permission for the role
          type: boolean
      required:
      - code
      - status
    UpdateRolePermissions_data_attributes:
      properties:
        permissions:
          description: An ordered list of role IDs representing the new roles hierarchy
          items:
            $ref: "#/components/schemas/UpdateRolePermissions_data_attributes_permissions_inner"
          type: array
    UpdateRolePermissions_data:
      properties:
        id:
          description: role ID
          format: uuid
          type: string
        type:
          enum:
          - update_roles_permission
          type: string
        attributes:
          $ref: "#/components/schemas/UpdateRolePermissions_data_attributes"
      required:
      - attributes
      - id
      - type
    Organization_data_attributes:
      properties:
        status:
          description: The status of the organization
          type: string
        name:
          description: The name of the organization
          type: string
        icon:
          description: The icon representing the organization
          type: string
        created_at:
          description: The date and time when the organization was created
          format: date-time
          type: string
        updated_at:
          description: The date and time when the organization was last updated
          format: date-time
          type: string
      required:
      - created_at
      - name
      - status
      - updated_at
    Organization_data:
      properties:
        id:
          description: organization ID
          format: uuid
          type: string
        type:
          enum:
          - organization
          type: string
        attributes:
          $ref: "#/components/schemas/Organization_data_attributes"
      required:
      - attributes
      - id
      - type
    Member_data_attributes:
      properties:
        account_id:
          description: The ID of the account associated with the member
          format: uuid
          type: string
        organization_id:
          description: The ID of the organization the member belongs to
          format: uuid
          type: string
        position:
          description: The position or role of the member within the organization
          type: string
        label:
          description: A label or title associated with the member
          type: string
        username:
          description: The username of the member
          type: string
        official:
          description: Indicates if the member is an official representative of the
            organization
          type: boolean
        created_at:
          description: The date and time when the member was created
          format: date-time
          type: string
        updated_at:
          description: The date and time when the member was last updated
          format: date-time
          type: string
      required:
      - account_id
      - created_at
      - official
      - organization_id
      - updated_at
      - username
    Member_data:
      properties:
        id:
          description: member ID
          format: uuid
          type: string
        type:
          enum:
          - member
          type: string
        attributes:
          $ref: "#/components/schemas/Member_data_attributes"
      required:
      - attributes
      - id
      - type
    Invite_data_attributes:
      properties:
        organization_id:
          description: The ID of the organization to which the invite belongs
          format: uuid
          type: string
        account_id:
          description: The ID of the account that was invited
          format: uuid
          type: string
        status:
          description: The status of the invite
          enum:
          - sent
          - accepted
          - declined
          type: string
        expires_at:
          description: The expiration date and time of the invite
          format: date-time
          type: string
        created_at:
          description: The date and time when the invite was created
          format: date-time
          type: string
      required:
      - account_id
      - created_at
      - expires_at
      - organization_id
      - status
    Invite_data:
      properties:
        id:
          description: invite ID
          format: uuid
          type: string
        type:
          enum:
          - invite
          type: string
        attributes:
          $ref: "#/components/schemas/Invite_data_attributes"
      required:
      - attributes
      - id
      - type
    Role_data_attributes:
      properties:
        organization_id:
          description: The ID of the organization this role belongs to
          format: uuid
          type: string
        head:
          description: Indicates if this role is the head role of the organization
          type: boolean
        rank:
          description: The rank of the role within the organization
          format: uint
          type: integer
        name:
          description: The name of the role
          type: string
        description:
          description: A brief description of the role
          type: string
        color:
          description: The color associated with the role in HEX format
          type: string
        created_at:
          description: Timestamp when the role was created
          format: date-time
          type: string
        updated_at:
          description: Timestamp when the role was last updated
          format: date-time
          type: string
      required:
      - color
      - created_at
      - description
      - head
      - name
      - organization_id
      - rank
      - updated_at
    Role_data_relationships_permissions_inner:
      properties:
        id:
          description: Unique identifier for the permission
          format: uuid
          type: string
        code:
          description: A short code representing the permission
          example: agglmeration.manage
          type: string
        description:
          description: A detailed description of what the permission allows
          example: Allows managing organization
          type: string
        enabled:
          description: Indicates if the role has this permission
          type: boolean
      required:
      - code
      - description
      - enabled
      - id
    Role_data_relationships:
      properties:
        permissions:
          items:
            $ref: "#/components/schemas/Role_data_relationships_permissions_inner"
          type: array
    Role_data:
      properties:
        id:
          description: member ID
          format: uuid
          type: string
        type:
          enum:
          - role
          type: string
        attributes:
          $ref: "#/components/schemas/Role_data_attributes"
        relationships:
          $ref: "#/components/schemas/Role_data_relationships"
      required:
      - attributes
      - id
      - type
    RolePermissions_data_inner:
      properties:
        id:
          description: Unique identifier for the permission
          format: uuid
          type: string
        code:
          description: A short code representing the permission
          example: agglmeration.manage
          type: string
        description:
          description: A detailed description of what the permission allows
          example: Allows managing organization
          type: string
      required:
      - code
      - description
      - id
