openapi: 3.1.0
info:
  description: API documentation for cities-svc
  title: cities-svc API
  version: 0.1.0
servers:
- url: /
paths:
  /test:
    post:
      description: Test
      responses:
        "201":
          description: successfully
      tags:
      - Test
components:
  schemas:
    CreateAgglomeration:
      properties:
        data:
          $ref: "#/components/schemas/CreateAgglomeration_data"
      required:
      - data
    UpdateAgglomeration:
      properties:
        data:
          $ref: "#/components/schemas/UpdateAgglomeration_data"
      required:
      - data
    Agglomeration:
      properties:
        data:
          $ref: "#/components/schemas/Agglomeration_data"
      required:
      - data
    AgglomerationsCollection:
      properties:
        data:
          items:
            $ref: "#/components/schemas/Agglomeration/properties/data"
          type: array
        links:
          $ref: "#/components/schemas/PaginationData"
      required:
      - data
      - links
    PaginationData:
      properties:
        self:
          description: link to the current page
          format: uri
          type: string
        first:
          description: link to the first page
          format: uri
          type: string
        last:
          description: link to the last page
          format: uri
          type: string
        prev:
          description: link to the previous page
          format: uri
          type: string
        next:
          description: link to the next page
          format: uri
          type: string
      required:
      - self
    data:
      properties:
        id:
          description: agglomeration ID
          format: uuid
          type: string
        type:
          enum:
          - agglomeration
          type: string
        attributes:
          $ref: "#/components/schemas/Agglomeration_data_attributes"
      required:
      - attributes
      - id
      - type
    CreateAgglomeration_data_attributes:
      properties:
        name:
          description: The name of the agglomeration
          type: string
        icon:
          description: The icon representing the agglomeration
          type: string
      required:
      - name
    CreateAgglomeration_data:
      properties:
        type:
          enum:
          - agglomeration
          type: string
        attributes:
          $ref: "#/components/schemas/CreateAgglomeration_data_attributes"
      required:
      - attributes
      - type
    UpdateAgglomeration_data_attributes:
      properties:
        name:
          description: The name of the agglomeration
          type: string
        icon:
          description: The icon representing the agglomeration
          type: string
    UpdateAgglomeration_data:
      properties:
        id:
          description: agglomeration ID
          format: uuid
          type: string
        type:
          enum:
          - agglomeration
          type: string
        attributes:
          $ref: "#/components/schemas/UpdateAgglomeration_data_attributes"
      required:
      - attributes
      - id
      - type
    Agglomeration_data_attributes:
      properties:
        status:
          description: The status of the agglomeration
          type: string
        name:
          description: The name of the agglomeration
          type: string
        icon:
          description: The icon representing the agglomeration
          type: string
        created_at:
          description: The date and time when the agglomeration was created
          format: date-time
          type: string
        updated_at:
          description: The date and time when the agglomeration was last updated
          format: date-time
          type: string
      required:
      - created_at
      - icon
      - name
      - status
      - updated_at
    Agglomeration_data:
      properties:
        id:
          description: agglomeration ID
          format: uuid
          type: string
        type:
          enum:
          - agglomeration
          type: string
        attributes:
          $ref: "#/components/schemas/Agglomeration_data_attributes"
      required:
      - attributes
      - id
      - type
